---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alnaggaar/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --prefer-dist --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan storage:link
